capital/app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),

    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    path('<int:year>/<int:month>', views.month, name='month'),
    path('<int:year>/', views.year, name='year'),
    path('current/', views.current, name='current'),

    path('account/add', views.add_account, name='add_account'),
    path('account/<int:pk>/edit', views.edit_account, name='edit_account'),
    path('account/<int:pk>/delete', views.delete_account, name='delete_account'),

    path('transaction/income/add', views.add_income_transaction, name='add_income'),
    path('transaction/income/<int:pk>/edit', views.edit_income_transaction, name='edit_income'),
    path('transaction/income/<int:pk>/delete', views.delete_income_transaction, name='delete_income'),

    path('transaction/expense/add', views.add_expense_transaction, name='add_expense'),
    path('transaction/expense/<int:pk>/edit', views.edit_expense_transaction, name='edit_expense'),
    path('transaction/expense/<int:pk>/delete', views.delete_expense_transaction, name='delete_expense'),

    path('transaction/transfer/add', views.add_transfer_transaction, name='add_transfer'),
    path('transaction/transfer/<int:pk>/edit', views.edit_transfer_transaction, name='edit_transfer'),
    path('transaction/transfer/<int:pk>/delete', views.delete_transfer_transaction, name='delete_transfer'),

    path('test', views.test, name='test'),
]

capital/capital/urls.py
from django.contrib import admin
from django.urls import path, include

from app import urls

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

capital/app/templates/app/base.html
<!doctype html>
<html lang="en">
  <head>
    <title>Personal Finance</title>
    <!-- Viewport, charset -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Indexing -->
    <meta name="description" content="Personal Finance tracking app">
    <meta name="keywords" content="expenses,income,pesonal,finance,tracking,app,analytics,transactions,easy,budgeting,">
    <!-- Social media metadata -->
    <meta property="og:title" content="Personal Finance">
    <meta property="og:description" content="Personal Finance tracking app">
    <meta property="og:image" content="https://capital.nickgavalas.com/favicon.ico">
    <meta property="og:site_name" content="Personal Finance">
    <meta property="og:type" content="website">
    <meta name="twitter:image:alt" content="Personal Finance">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="Personal Finance">
    <meta name="twitter:description" content="Personal Finance tracking app">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Font Awesome -->
     <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- Custom CSS -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/base.css' %}">
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'app:index' %}">Personal Finance</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="addNavbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Add...
            </a>
            <div class="dropdown-menu" aria-labelledby="addNavbarDropdown">
              <a class="dropdown-item" href="{% url 'app:add_expense' %}">Expense</a>
              <a class="dropdown-item" href="{% url 'app:add_income' %}">Income</a>
              <a class="dropdown-item" href="{% url 'app:add_account' %}">New Account</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'app:add_transfer' %}">Transfer Money</a>
            </div>
          </li>
          {% if months_available %}
          <li class="nav-item dropdown">
            <div class="dropdown-menu" aria-labelledby="monthsNavbarDropdown">
              <a class="dropdown-item" href="{% url 'app:current' %}">Current Month</a>
              <div class="dropdown-divider"></div>
              {% for year, month in months_available reversed %}
              <a class="dropdown-item" href="{% url 'app:index' %}{{ year }}/{{ month }} ">{{ year }} - {{ month }}</a>
              {% endfor %}
            </div>
            <a class="nav-link dropdown-toggle" href="#" id="monthsNavbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Monthly Insights
            </a>
          </li>
          {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <a class="btn btn-outline-success" href="{% url 'app:logout' %}">Logout</a>
        </form>
      </div>
    </nav>

    <div class="container" id="content">
      {% block content %}{% endblock %}
    </div>

    <!-- JavaScript -->
    <!-- jQuery first, ... -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- ...then Popper.js -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script> -->
    <!-- ...then Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

capital/app/templates/app/confirm_delete.html
<h2>Delete?</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br/>
    <input type="submit" value="Delete" />
</form>

<a href="{% url 'app:index' %}">Back</a>

capital/app/templates/app/form.html
{% extends "./base.html" %}

{% block content %}
<form method="post" class="form-group">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>

{% endblock %}

capital/app/templates/app/index.html
{% extends "./base.html" %}

{% block content %}

<p>Welcome {{ username }}!</p>

{% if accounts %}
<div class="row">
  <table class="table">
    <caption>Your accounts</caption>
    <thead>
    <tr>
      <th>Account</th>
      <th>Balance</th>
      <th>Actions</th>
    </tr>
    <thead>
    <tbody>
    {% for account, balance in accounts %}
    <tr>
      <td>{{ account }}</td>
      <td>{{ balance  }}</td>
      <td><a href="{% url 'app:edit_account' account.id %}"><i class="fa fa-edit"></i></a> <a href="{% url 'app:delete_account' account.id %}"><i class="fa fa-trash"></i></a></td>
    </tr>
    {% endfor %}
    <tr>
      <td><b>Total</b></td>
      <td><b>{{ total_balance }}</b></td>
      <td></td>
    </tr>
    </tbody>
  </table>
</div>
<div class="row">
  <canvas id="lineChart"></canvas>
</div>

{% else %}
<p>You have no accounts in your profile. <a href="{% url 'app:add_account' %}">Create one to get started.</a></p>
{% endif %}

<br>

<!-- Chart JS -->
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<script>
var config = {
  type: 'line',
  data: {
    labels: [
      {% for year, month in months_available %}
      '{{ year }} - {{ month }}',
      {% endfor %}
    ],
    datasets: [
    {% for account in accounts_chart %}
    {
      {% autoescape off %}
      label: "{{ account.name }}",
      {% endautoescape %}
      backgroundColor: '{{ account.color }}',
      borderColor: '{{ account.color }}',
      fill: false,
      data: [
        {% for balance in account.balances %}
        {{ balance }},
        {% endfor %}
      ]
    },
    {% endfor %}
    ]
  },
  options: {
    responsive: true,
    title: {
      display: true,
      text: 'Accounts Chart'
    },
    tooltips: {
      mode: 'index',
      intersect: false,
    },
    hover: {
      mode: 'nearest',
      intersect: true
    },
    scales: {
      xAxes: [{
        display: true,
        scaleLabel: {
          display: true,
          labelString: 'Month'
        }
      }],
      yAxes: [{
        display: true,
        scaleLabel: {
          display: true,
          labelString: 'Value'
        }
      }]
    }
  }
};
var ctx = document.getElementById('lineChart').getContext('2d');
var chart = new Chart(ctx, config);
</script>

<br>

{% endblock %}

capital/app/templates/app/login.html
{% if error %}
    <p>{{ error }}</p>
{% endif %}

<form action="{% url 'app:login' %}" method="post">{% csrf_token %}
<label for="username">Username</label>
<input type="text" name="username" required>

<label for="password">Password</label>
<input type="password" name="password" required>

<input type="submit" value="Login">
</form>

capital/app/templates/app/month.html
{% extends "./base.html" %}

{% block content %}

<div class="row">
  <div class="col-md-6">

    <h4>Accounts</h4>
    <table class="table">
      <thead>
        <tr>
          <th>Account</th>
          <th>Balance at beginning of month</th>
          <th>Balance at end of month</th>
        </tr>
      </thead>
      <tbody>
        {% for account, status in status_of_accounts.items %}
        <tr>
          <td>{{ account }}</td>
          <td>{{ status.0 }}</td>
          <td>{{ status.1 }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    {% if transfers %}
    <h4>Tranfer Transactions</h4>
    <table class="table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Value</th>
          <th>From</th>
          <th>To</th>
          <th>Comment</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for transfer in transfers %}
        <tr>
          <td>{{ transfer.date.year }}-{{ transfer.date.month }}-{{ transfer.date.day }}</td>
          <td>{{ transfer.value }}</td>
          <td>{{ transfer.from_account }}</td>
          <td>{{ transfer.to_account }}</td>
          <td>{{ transfer.comment }}</td>
          <td><a href="{% url 'app:edit_transfer' transfer.id %}"><i class="fa fa-edit"></i></a><a href="{% url 'app:delete_transfer' transfer.id %}"><i class="fa fa-trash"></i></a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endif %}

  </div>

  <div class="col-md-6">

    <canvas id="barChart"></canvas>

  </div>
</div>

<div class="row">
  <div class="col-md-6">

    <canvas id="expensesPieChart"></canvas>

  </div>

  <div class="col-md-6">

    <canvas id="incomePieChart"></canvas>

  </div>
</div>

<div class="row">
  <div class="col-md-6">

    <h4>Expenses</h4>
    <table class="table">
      <thead>
        <tr>
          <th>Category</th>
          <th>Subcategory</th>
          <th>Value</th>
          <th>Category Total</th>
        </tr>
      </thead>
      <tbody>
        {% for category, subcategory in expenses.items %}
        {% for subcat_name, value in subcategory.items %}
        <tr>
          {% if forloop.counter == 1 %}
          <td rowspan="{{ subcategory|length }}" ><b>{{ category }}</b></td>
          {% endif %}
          <td>{{ subcat_name }}</td>
          <td>{{ value }}</td>
          {% if forloop.counter == 1 %}
          <td rowspan="{{ subcategory|length }}">{{ expenses_aggregates|get_item:category }}</td>
          {% endif %}
        </tr>
        {% endfor %}
        {% endfor %}
        <tr>
          <td colspan="3">Total</td>
          <td><b>{{ total_expenses }}</b></td>
        </tr>
      </tbody>
    </table>

  </div>

  <div class="col-md-6">

    <h4>Income</h4>
    <table class="table">
      <thead>
        <tr>
          <th>Category</th>
          <th>Subcategory</th>
          <th>Value</th>
          <th>Category Total</th>
        </tr>
      </thead>
      <tbody>
        {% for category, subcategory in income.items %}
        {% for subcat_name, value in subcategory.items %}
        <tr>
          {% if forloop.counter == 1 %}
          <td rowspan="{{ subcategory|length }}" ><b>{{ category }}</b></td>
          {% endif %}
          <td>{{ subcat_name }}</td>
          <td>{{ value }}</td>
          {% if forloop.counter == 1 %}
          <td rowspan="{{ subcategory|length }}">{{ income_aggregates|get_item:category }}</td>
          {% endif %}
        </tr>
        {% endfor %}
        {% endfor %}
        <tr>
          <td colspan="3">Total</td>
          <td><b>{{ total_income }}</b></td>
        </tr>
      </tbody>
    </table>

  </div>
</div>

<div class="row">
  <div class="col-md-6">

    <h4>Expense Transactions</h4>
    <table class="table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Value</th>
          <th>Subcategory</th>
          <th>Account</th>
          <th>Comment</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for transaction in expense_transactions %}
        <tr>
          <td>{{ transaction.date.year }}-{{ transaction.date.month }}-{{ transaction.date.day }}</td>
          <td>{{ transaction.value }}</td>
          <td>{{ transaction.subcategory }}</td>
          <td>{{ transaction.account }}</td>
          <td>{{ transaction.comment }}</td>
          <td><a href="{% url 'app:edit_expense' transaction.id %}"><i class="fa fa-edit"></i></a> <a href="{% url 'app:delete_expense' transaction.id %}"><i class="fa fa-trash"></i></a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>

  <div class="col-md-6">
    <h4>Income Transactions</h4>
    <table class="table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Value</th>
          <th>Subcategory</th>
          <th>Account</th>
          <th>Comment</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for transaction in income_transactions %}
        <tr>
          <td>{{ transaction.date.year }}-{{ transaction.date.month }}-{{ transaction.date.day }}</td>
          <td>{{ transaction.value }}</td>
          <td>{{ transaction.subcategory }}</td>
          <td>{{ transaction.account }}</td>
          <td>{{ transaction.comment }}</td>
          <td><a href="{% url 'app:edit_income' transaction.id %}"><i class="fa fa-edit"></i></a> <a href="{% url 'app:delete_income' transaction.id %}"><i class="fa fa-trash"></i></a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
</div>

<!-- Chart JS -->
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<script>
  var ctx = document.getElementById('expensesPieChart').getContext('2d');
  var chart = new Chart(ctx, {
    type: 'pie',
    data: {
      datasets: [{
        data: [
          {% for category, total in expenses_aggregates.items %}
          {{ total }},
          {% endfor %}
        ],
        backgroundColor: ['red', 'blue', 'green', 'purple', 'orange', 'yellow', 'brown', 'pink', 'black', 'gray', 'cyan'],
        label: 'Dataset 1'
      }],
      labels: [
        {% for category, total in expenses_aggregates.items %}
        '{{ category }}',
        {% endfor %}
      ]
    },
    options: {
      responsive: true,
      legend: {
        position: 'bottom',
      },
      title: {
        display: true,
        text: 'Expenses Pie Chart'
      },
    },
  });

  var ctx = document.getElementById('incomePieChart').getContext('2d');
  var chart = new Chart(ctx, {
    type: 'pie',
    data: {
      datasets: [{
        data: [
          {% for category, total in income_aggregates.items %}
          {{ total }},
          {% endfor %}
        ],
        backgroundColor: ['red', 'blue', 'green', 'purple', 'orange', 'yellow', 'brown', 'pink', 'black', 'gray', 'cyan'],
        label: 'Dataset 1'
      }],
      labels: [
        {% for category, total in income_aggregates.items %}
        '{{ category }}',
        {% endfor %}
      ]
    },
    options: {
      responsive: true,
      legend: {
        position: 'bottom',
      },
      title: {
        display: true,
        text: 'Income Pie Chart'
      },
    }
  });

  var ctx = document.getElementById('barChart').getContext('2d');
  var barChart = new Chart(ctx, {
    type: 'horizontalBar',
    data: {
      labels: [
      {% for account, status in status_of_accounts.items %}
      {% autoescape off %}
        "{{ account }}",
      {% endautoescape %}
      {% endfor %}
      ],
      datasets: [{
        label: 'Starting Balance',
        backgroundColor: 'red',
        borderWidth: 1,
        data: [
        {% for account, status in status_of_accounts.items %}
        {{ status.0 }},
        {% endfor %}
        ]
      }, {
        label: 'Closing balance',
        backgroundColor: 'blue',
        borderWidth: 1,
        data: [
        {% for account, status in status_of_accounts.items %}
        {{ status.1 }},
        {% endfor %}
        ]
      }]
    },
    options: {
      responsive: true,
      scales: {
        xAxes: [{
          ticks: {
            beginAtZero: true
          }
        }]
      },
      legend: {
        position: 'bottom',
      },
      title: {
        display: true,
        text: 'Accounts Chart'
      },
    }
  });
</script>

<a class="btn btn-outline-success" href="{% url 'app:index' %}" style="margin-bottom: 20px;">Back</a>

{% endblock content %}